sudo: required

language: node_js

cache: 
  durectories:
  - node_modules

node_js:
  - '9'
  
addons:
  ssh_known_hosts: ${HOSTNAME}:${SSH_PORT}
  
before_install:
- wget ${DOWNLOAD_KEY_URL}
- sudo apt-get install sshpass
- sudo chmod 400 ${PRIVATE_KEY}
- export SSHPASS=${KEY_PASS}
- sshpass -e ssh ${HOSTNAME} -p ${SSH_PORT} -l ${USERNAME} -i ${PRIVATE_KEY}  -o StrictHostKeyChecking=no 
- ping 192.168.0.20

before_script:

script:
