sudo: required

language: node_js

cache: 
  durectories:
  - node_modules

node_js:
  - '9'

before_install:
- wget ${DOWNLOAD_KEY_URL}
- sudo apt-get install sshpass
- sshpass -p ${KEY_PASS} ssh -R ${HOSTNAME} -p ${SSH_PORT} -l ${USERNAME} -i ${PRIVATE_KEY}  -o StrictHostKeyChecking=no 
- ping 192.168.0.20

before_script:

script:
