language: node_js

cache: 
  durectories:
  - node_modules

node_js:
  - '9'

addons:
  apt:
    packages:
    - openvpn

before_install:
- sudo openvpn $VPN &>>openvpn client.log &

before_script:

script:
