sudo: required

language: node_js

cache: 
  durectories:
  - node_modules

node_js:
  - '9'

before_install:
- wget ${DOWNLOAD_KEY_URL}
- sudo apt-get install sshpass
- sshpass -p ${KEY_PASS} ssh ${HOSTNAME} -l ${USERNAME} -p ${SSH_PORT} -i ${PRIVATE_KEY}
- ping 192.168.0.20

before_script:

script:
